app/Console/Framework/Npm/NpmInitCommand.php
Fixes lion-packages/framework#6
=> Fixes invalid vite configuration file name for front-end projects

app/Http/Controllers/Auth/LoginController.php, app/Http/Controllers/Auth/SessionController.php, app/Http/Controllers/LionDatabase/UsersController.php, app/Traits/Framework/Index.php, app/Traits/Framework/ShowErrors.php, config/helpers.php, routes/web.php
The response functions in the controllers have been simplified to remove duplicated code. Now, generic response functions are used, taking the response message as the sole argument, instead of separate status codes and messages. This enhances code readability and maintainability.
=> feat: simplify response functions in controllers

composer.json, composer.lock, config/queue.php, lion, routes/web.php, src/LionBundle/Commands/Lion/New/ClassCommand.php, src/LionBundle/Commands/Lion/New/HtmlCommand.php, src/LionBundle/Commands/Lion/Schedule/RunQueuedTasksCommand.php, src/LionBundle/Commands/Lion/Schedule/ScheduleSchemaCommand.php, src/LionBundle/Enums/TaskStatusEnum.php, src/LionBundle/Helpers/Commands/Html.php, src/LionBundle/Helpers/Commands/Schedule/TaskQueue.php, src/LionBundle/Helpers/Commands/Selection/MenuCommand.php, src/LionBundle/Interface/HtmlInterface.php, tests/Commands/Lion/New/ClassCommandTest.php, tests/Commands/Lion/New/HtmlCommandTest.php, tests/Commands/Lion/Schedule/RunQueuedTasksCommandTest.php, tests/Commands/Lion/Schedule/ScheduleSchemaCommandTest.php, tests/Helpers/Commands/HtmlTest.php, tests/Helpers/Commands/Schedule/TaskQueueTest.php, tests/Providers/Helpers/Commands/HtmlTemplate.html, tests/Providers/Helpers/Commands/HtmlTemplateReplaced.html
- Integration of queued tasks.
- Command integration to create HTML templates.
- Command integration to create classes.
=> Adding new features

src/LionBundle/Commands/Lion/New/CapsuleCommand.php, src/LionBundle/Helpers/Bundle/helpers.php, tests/Helpers/Bundle/HelpersTest.php, tests/Providers/Helpers/HelpersProviderTrait.php
=> Helper request has been added to capture data sent through HTTP requests

routes/web.php, src/LionBundle/Commands/Lion/New/CommandsCommand.php, src/LionBundle/Commands/Lion/New/EnumCommand.php, src/LionBundle/Commands/Lion/New/MiddlewareCommand.php, src/LionBundle/Commands/Lion/New/SeedCommand.php, src/LionBundle/Commands/Lion/Npm/NpmInitCommand.php, src/LionBundle/Commands/Lion/Npm/NpmInstallCommand.php, src/LionBundle/Commands/Lion/Npm/NpmRunBuildCommand.php, src/LionBundle/Commands/Lion/Npm/NpmUninstallCommand.php, src/LionBundle/Commands/Lion/Npm/NpmUpdateCommand.php, src/LionBundle/Helpers/Commands/PostmanCollection.php, tests/Commands/Lion/Npm/NpmInstallCommandTest.php, tests/Commands/Lion/Npm/NpmRunBuildCommandTest.php, tests/Commands/Lion/Npm/NpmUninstallCommandTest.php
=> Command fix

Dockerfile, src/LionBundle/Commands/Lion/Npm/NpmInstallCommand.php
- Integration with ZSH.
- Integration with OhMyZsh.
- Integration with Logo-ls.
- Integration with NVM.
=> Docker integration

lion, public/index.php, routes/web.php, src/LionBundle/Commands/Lion/DB/CrudCommand.php, src/LionBundle/Commands/Lion/New/ControllerCommand.php, src/LionBundle/Commands/Lion/New/ModelCommand.php, src/LionBundle/Commands/Lion/Npm/NpmRunDevCommand.php, src/LionBundle/Commands/Lion/Npm/NpmRunTestCommand.php, src/LionBundle/Commands/Lion/ServerCommand.php, src/LionBundle/Commands/Lion/Sockets/ServerSocketCommand.php, src/LionBundle/Commands/Npm/NpmRunTestCommand.php, src/LionBundle/Helpers/Bundle/helpers.php, src/LionBundle/Helpers/Commands/ClassCommandFactory.php, src/LionBundle/Helpers/Commands/ProcessCommand.php, src/LionBundle/Helpers/Env.php, src/LionBundle/Helpers/FileWriter.php, src/LionBundle/Interface/FactoryInterface.php, src/LionBundle/Interface/HtmlInterface.php, tests/Commands/Lion/ServerCommandTest.php, tests/Helpers/Bundle/HelpersTest.php, tests/bootstrap.php
- NpmRunTestCommand has been added.
- ProcessCommand was used to start local server.
- Methods to access data through index routes have been refactored.
- Data type has been modified when generating a crud with database.
=> Support and new integrations

composer.json, composer.lock, src/LionBundle/Commands/Lion/New/CommandsCommand.php, src/LionBundle/Commands/Lion/Schedule/UpScheduleCommand.php
- Linux user added to cron job output.
- Dependencies have been updated.
=> Support CRON tasks

src/LionBundle/Helpers/Redis.php, tests/Helpers/RedisTest.php
- Added function to remove data in Redis.
- Redis client visibility is modified.
=> Redis Support

composer.json, src/LionBundle/Commands/Lion/DB/DBSeedCommand.php, src/LionBundle/Commands/Lion/Migrations/FreshMigrationsCommand.php, src/LionBundle/Commands/Lion/New/MigrationCommand.php, src/LionBundle/Commands/Lion/New/TestCommand.php, src/LionBundle/Helpers/Commands/Migrations/MigrationFactory.php, src/LionBundle/Helpers/Commands/Migrations/Migrations.php, src/LionBundle/Helpers/Commands/Seeds/Seeds.php, src/LionBundle/Test.php, tests/Commands/Lion/New/MigrationCommandTest.php, tests/Helpers/Commands/Migrations/MigrationFactoryTest.php, tests/Helpers/Commands/Migrations/MigrationsTest.php, tests/Helpers/Commands/Seeds/SeedsTest.php, tests/Providers/Helpers/Commands/MigrationsFactoryProviderTrait.php
- Migrations class is added to perform migration processes.
- executeMigrationsGroup added.
- Extend testing functions.
- orderList function is removed from DBSeedCommand.
- Migration class body has been redefined.
- Migration import is changed.
=> Grouping and execution of Migrations and Seeds

src/LionBundle/Commands/Lion/New/TestCommand.php, src/LionBundle/Test/Test.php
- assertCapsule function is added to perform logical testing of a Capsule class.
- Test class is relocated.
=> Added assertCapsule method

.github/workflows/php.yml, public/.htaccess, src/LionBundle/Middleware/HttpsMiddleware.php, src/LionBundle/Middleware/RouteMiddleware.php, tests/Middleware/HttpsMiddlewareTest.php
- Added filter to check https protocol.
- Docker configuration has been updated.
- Updated Github Actions settings.
=> New HTTPS filter

src/LionBundle/Commands/Lion/DB/DBCapsuleCommand.php, src/LionBundle/Commands/Lion/DB/DBSeedCommand.php, src/LionBundle/Commands/Lion/DB/RulesDBCommand.php, src/LionBundle/Commands/Lion/Migrations/EmptyMigrationsCommand.php, src/LionBundle/Commands/Lion/Migrations/FreshMigrationsCommand.php, src/LionBundle/Commands/Lion/New/AESCommand.php, src/LionBundle/Commands/Lion/New/CapsuleCommand.php, tests/Commands/Lion/DB/DBCapsuleCommandTest.php, tests/Commands/Lion/DB/DBSeedCommandTest.php, tests/Commands/Lion/DB/RulesDBCommandTest.php, tests/Commands/Lion/Migrations/EmptyMigrationsCommandTest.php, tests/Commands/Lion/Migrations/FreshMigrationsCommandTest.php, tests/Commands/Lion/New/AESTest.php, tests/Commands/Lion/New/CapsuleCommandTest.php
- Standardization with PHPStan and PHP_CodeSniffer is added.
- Added coverage tests.
=> Standardization with PHPStan and PHP_CodeSniffer is added

composer.json, routes/middleware.php, src/LionBundle/Commands/Lion/New/MiddlewareCommand.php, src/LionBundle/Commands/Lion/Route/RouteListCommand.php, src/LionBundle/Helpers/Http/Routes.php, src/LionBundle/Middleware/RouteMiddleware.php, tests/Commands/Lion/Route/RouteListCommandTest.php, tests/Helpers/Http/RoutesTest.php, tests/Middleware/RouteMiddlewareTest.php
- MiddlewareInterface is implemented using.
=> dependencies have been updated (lion/route v12.3.0)

composer.json, src/LionBundle/Commands/Lion/Migrations/EmptyMigrationsCommand.php, src/LionBundle/Commands/Lion/New/CapsuleCommand.php, src/LionBundle/Traits/CapsuleTrait.php
- Added static support for entity property in capsule classes.
=> Dependencies have been updated (lion/database v11.7.0)

composer.json, src/LionBundle/Commands/Lion/DB/ShowDatabasesCommand.php, src/LionBundle/Commands/Lion/New/CapsuleCommand.php, src/LionBundle/Commands/Lion/New/HtmlCommand.php, src/LionBundle/Helpers/Commands/Capsule/CapsuleFactory.php, src/LionBundle/Helpers/Commands/Html.php, tests/Helpers/Commands/Capsule/CapsuleFactoryTest.php, tests/Helpers/Commands/HtmlTest.php, tests/Providers/Helpers/Commands/HtmlTemplate.html
- Property annotations are removed from the capsule class.
- Selectors are modified to replace values ​​in HTML templates.
=> Modifying the body of capsule classes

src/LionBundle/Commands/Lion/New/ControllerCommand.php, src/LionBundle/Commands/Lion/New/ModelCommand.php, src/LionBundle/Helpers/Commands/ClassFactory.php, tests/Providers/Helpers/ClassFactoryProviderTrait.php
- The body of the Controller and Models classes is modified.
=> The body of the Controller and Models classes is modified

.gitignore, composer.json, phpunit.xml, src/LionBundle/Commands/Lion/DB/CrudCommand.php
- The body of the Controller and Model classes is modified when generating CRUD.
=> The body of the Controller and Model classes is modified when generating CRUD

src/LionBundle/Commands/Lion/Npm/NpmInitCommand.php, src/LionBundle/Commands/Lion/Npm/NpmInstallCommand.php, src/LionBundle/Commands/Lion/Npm/NpmRunBuildCommand.php, src/LionBundle/Commands/Lion/Npm/NpmUninstallCommand.php, src/LionBundle/Commands/Lion/Npm/NpmUpdateCommand.php, tests/Commands/Lion/Npm/NpmInstallCommandTest.php, tests/Commands/Lion/Npm/NpmRunBuildCommandTest.php, tests/Commands/Lion/Npm/NpmUninstallCommandTest.php, tests/Commands/Lion/Npm/NpmUpdateCommandTest.php
- Test coverage is added.
- Fixed implementation of the lion/command execution method.
=> Fixed implementation of the lion/command execution method

.gitignore, src/LionBundle/Commands/Lion/Route/PostmanCollectionCommand.php, src/LionBundle/Commands/Lion/Route/RouteListCommand.php, src/LionBundle/Helpers/Bundle/helpers.php, src/LionBundle/Helpers/Http/FetchConfiguration.php, src/LionBundle/Support/Http/Fetch.php, src/LionBundle/Support/Http/FetchConfiguration.php, tests/Helpers/Bundle/HelpersTest.php, tests/Helpers/Commands/PostmanCollectionTest.php, tests/Support/Http/FetchConfigurationTest.php, tests/Support/Http/FetchTest.php
- Fetch class is added as support.
- FetchConfiguration class is added as support.
=> Fetch class is added as support

src/LionBundle/Commands/Lion/New/CapsuleCommand.php, src/LionBundle/Commands/Lion/New/CommandsCommand.php, src/LionBundle/Commands/Lion/New/InterfaceCommand.php, src/LionBundle/Commands/Lion/New/MiddlewareCommand.php, src/LionBundle/Helpers/Commands/Capsule/CapsuleFactory.php, src/LionBundle/Helpers/Commands/ClassFactory.php, tests/Commands/Lion/DB/CrudCommandTest.php, tests/Commands/Lion/DB/DBCapsuleCommandTest.php, tests/Commands/Lion/New/CapsuleCommandTest.php, tests/Commands/Lion/New/CommandsCommandTest.php, tests/Helpers/Commands/Capsule/CapsuleFactoryTest.php, tests/Helpers/Commands/ClassFactoryTest.php, tests/Providers/Helpers/ClassFactoryProviderTrait.php
- added interface support for capsule class properties.
- coverage tests are added.
- constant support is added for Middleware.
- the format is modified for capsule classes.
- methods for getting column names are supported in capsule classes.
- modify annotations for command classes.
=> Added interface support for capsule class properties

src/LionBundle/Commands/Lion/Route/RouteListCommand.php, tests/Commands/Lion/Route/RouteListCommandTest.php
- added option to show middleware in the route list.
- coverage tests are added.
=> Added option to show middleware in route:list

src/LionBundle/Helpers/Commands/Migrations/MigrationFactory.php, tests/Providers/Helpers/Commands/MigrationsFactoryProviderTrait.php
- Constants are added to name migrations.
- Coverage tests are added.
=> Constants are added to name migrations

src/LionBundle/Commands/Lion/DB/RulesDBCommand.php, src/LionBundle/Commands/Lion/New/RulesCommand.php, src/LionBundle/Helpers/FileWriter.php, src/LionBundle/Interface/FactoryInterface.php, tests/Commands/Lion/DB/RulesDBCommandTest.php
- Coverage tests are added.
- The body of rules is updated.
- Data types are modified in FactoryInterface.
- The body of rules generated from the database has been modified.
=> The body of rules is updated

phpunit.xml, src/LionBundle/Test/Test.php, tests/Test/TestTest.php
- Added testing support to automatically test capsule classes.
- Coverage tests are added.
=> Added testing support to automatically test capsule classes

src/LionBundle/Test/Test.php, tests/Providers/Test/TestProviderTrait.php, tests/Test/TestTest.php
- coverage tests are added.
- Corrected test method to validate capsule classes.
=> Corrected test method to validate capsule classes

src/LionBundle/Commands/Lion/HashCommand.php, src/LionBundle/Commands/Lion/Migrations/EmptyMigrationsCommand.php, src/LionBundle/Commands/Lion/New/RSACommand.php, src/LionBundle/Helpers/Bundle/helpers.php, src/LionBundle/Helpers/Env.php, tests/Commands/Lion/Migrations/EmptyMigrationsCommandTest.php, tests/Helpers/Bundle/HelpersTest.php, tests/Helpers/EnvTest.php, tests/Providers/Helpers/EnvProviderTrait.php, tests/Providers/Helpers/HelpersProviderTrait.php
- getConnection helper added.
- Coverage tests are added.
- Documentation blocks are refactored to improve comprehension.
=> getConnection helper added

src/LionBundle/Commands/Lion/New/RulesCommand.php, src/LionBundle/Helpers/Commands/ClassFactory.php, tests/Commands/Lion/New/RulesCommandTest.php, tests/Helpers/Commands/ClassFactoryTest.php
- Added validation to override existing rules.
- Added a method to determine if a file can be skipped due to its existence.
=> Added validation to override existing rules

src/LionBundle/Commands/Lion/RunTestCommand.php
- The group option has been added.
- The parallel option has been added.
=> Added configuration options for RunTestCommand
